[package]
name = "im"
version = "0.1.0"
edition = "2021"

description = "IM模块的Rust实现"

[dependencies]
cxx = "1.0"

# 需要用到多线程同步

[build-dependencies]
cxx-build = "1.0"

[lib]
name = "im"
path = "room.rs"
crate-type = ["rlib"]
