name: Build Qt Application

on:
  push:
    branches: [ "master" ] # 当主分支有更新时触发
  pull_request:
    branches: [ "master" ] # 当有 PR 到主分支时触发

jobs:
  build-windows:
    runs-on: windows-latest # 指定在 Windows 服务器上运行

    env:
      QT_VERSION: '6.5.0' # 这里设置环境变量，方便复用

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 检出你的代码

      - name: Install Qt
        # 使用一个非常方便的第三方 Action 来安装 Qt
        # 'aqtinstall' 是一个开源的 Qt 安装工具
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }} # 使用环境变量
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw' # 指定 MinGW 工具链
          modules: 'qtwebengine qtwebchannel' # 列出你需要的额外模块

      - name: Configure CMake
        run: cmake -S . -B build -G "MinGW Makefiles"

      - name: Build Project
        run: cmake --build build

      - name: Prepare Artifacts
        shell: cmd
        run: |
          REM 创建一个用于打包的文件夹
          mkdir deploy
          REM 拷贝可执行文件
          copy build\bin\QtWebSchoolSys.exe deploy\
          REM 拷贝你的 DLL
          copy build\lib\im_core.dll deploy\
          REM 拷贝 Vue 的 web 文件夹
          xcopy build\bin\web deploy\web\ /E /I
          REM 拷贝图标文件夹
          xcopy build\icons deploy\icons\ /E /I
          REM 使用 windeployqt 工具自动拷贝所有需要的 Qt DLLs
          "%Qt6_DIR%\bin\windeployqt.exe" deploy\QtWebSchoolSys.exe || ^
          C:\Qt\${{ env.QT_VERSION }}\mingw_64\bin\windeployqt.exe deploy\QtWebSchoolSys.exe

      - name: Upload Artifact
        # 将打包好的 deploy 文件夹作为一个构建产物上传
        uses: actions/upload-artifact@v4
        with:
          name: QtWebSchoolSys-Windows
          path: deploy/