name: Build Qt Application

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-windows:
    # 最终的现实：我们必须在最新的 Windows Runner 上运行
    runs-on: windows-latest

    env:
      # 坚持使用这个稳定的 LTS 版本
      QT_VERSION: '6.5.3'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 前端和 Python 步骤 (不变) ---
      - name: Set up pnpm and Node.js
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Set up Node.js for pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'web/vue-proj/pnpm-lock.yaml'
      - name: Install and Build Vue Project
        working-directory: ./web/vue-proj
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Python preprocessing script
        run: python config_qrc.py

      # --- C++/Qt 构建步骤 ---
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          # 使用与 VS 2022 ABI 兼容的 msvc2019 库
          arch: 'win64_msvc2019_64'
          modules: 'qtwebengine qtwebchannel'

      - name: Configure CMake
        # 【【【决定性修正 - 回归】】】
        # 在 windows-latest(VS2022) 环境下，我们必须手动提示 CMake 如何找到
        # WebEngineCore，以修复 WebEngineWidgets 的内部依赖查找问题。
        run: >
          cmake -S . -B build
          -D CMAKE_PREFIX_PATH="%Qt6_DIR%/lib/cmake/Qt6WebEngineCore"

      - name: Build Project with CMake
        run: cmake --build build --config Release

      - name: Prepare Artifacts for Upload
        shell: cmd
        run: |
          mkdir deploy
          copy build\Release\QtWebSchoolSys.exe deploy\
          copy build\Release\im_core.dll deploy\
          xcopy build\bin\web deploy\web\ /E /I
          xcopy build\icons deploy\icons\ /E /I
          echo "Running windeployqt..."
          "%Qt6_DIR%\bin\windeployqt.exe" --release --no-translations --no-opengl-sw deploy\QtWebSchoolSys.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtWebSchoolSys-Windows-Build
          path: deploy/